#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/background1.h"
#include "images/gameover1.h"
#include "images/bomb2.h"
#include "images/city2.h"

Bomb b;
Shield s;
char slowdown[51];

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  videoBuffer[1208] = 0x7fff;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        drawFullScreenImageDMA(background1);
        state = STARTTEXT;
        break;
      case STARTTEXT:
        drawString(60, 60, "Save the City", WHITE);
        if (KEY_DOWN(BUTTON_START, currentButtons)) {     
          state = PLAYEMPTY;
        }
        break;
      case PLAYEMPTY:
        drawFullScreenImageDMA(city2);
        state = PLAY;
        vBlankCounter = 0;
        break;
      case PLAY:
        playSave(&state); 
        break;
      case LOSE:
        drawFullScreenImageDMA(gameover1);
        state = LOSETEXT;
        break;
      case LOSETEXT:
        sprintf(slowdown, "SCORE: %d", s.score);
        drawRectDMA(120, 97, 55, 8, BLACK);
        drawString(120, 97, slowdown, WHITE);
        if (KEY_DOWN(BUTTON_START, currentButtons)) {   
          state = PLAYEMPTY;
        } else if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {     
          state = START;
        }
        break;
    }

    previousButtons = currentButtons;
  }

  UNUSED(previousButtons);

  return 0;
}

void Score(u16 color) {
  drawRectDMA(150, 5, 60, 8, BLACK);
  s.score = (vBlankCounter)/60;
  sprintf(slowdown, "SCORE: %d", s.score);
  drawString(150, 5, slowdown, WHITE);
  UNUSED(color);
}


void makeShield(void) {       
  s.col = 108;
  s.top = 120;
  s.step = s.top + 5;
  s.left = 108;
  s.right = s.left + 25;
  s.score = 0;
  drawRectDMA(120, s.col, 25, 5, WHITE);
}

Bomb setBomb(void) {                      
  Bomb b;
  b.row = randint(10, 40);
  b.col = randint(00, 160);
  b.right = b.col + 2;
  b.step = b.row + 2;
  drawImageDMA(b.row, b.col, 18, 10, bomb2);
  return b;
}

void playSave(gba_state *state) {       
 sprintf(slowdown, "SCORE: %d", s.score);
  makeShield();       
  b = setBomb();            
  int du = 1;    
  int rd = 1;     
  u32 buttons;
  while (*state == PLAY) {
    waitForVBlank();
    Score(BLACK);
    buttons = BUTTONS;
    if (KEY_DOWN(BUTTON_LEFT, buttons)) {    
      drawRectDMA(120, s.col, 25, 5, BLACK);
      s.col--;
      s.left--;
      s.right--;
      if (s.col <= 0) {
        s.col = 0;
        s.left = s.col;
        s.right = s.col + 25;
      }
      drawRectDMA(120, s.col, 25, 5, WHITE);
    }
    if (KEY_DOWN(BUTTON_RIGHT, buttons)) {    
      drawRectDMA(120, s.col, 25, 5, BLACK);
      s.col++;
      s.left++;
      s.right++;
      if (s.right >= 240) {
        s.right = 240;
        s.left = s.right - 25;
        s.col = s.left;
      }
      drawRectDMA(120, s.col, 25, 5, WHITE);
    }
    drawRectDMA(b.row, b.col, 18, 10, BLACK);   
    if (b.row < 0) {    
      du = 1;
      b.row = 0;
    } else if(b.row > 140) {      
      *state = LOSE;                    
      return;
    } 
    if(b.col < 0) {                 
      rd = 1;
      b.col = 0;
    } else if(b.col > 230) {        
      rd = -1;
      b.col = 230;
    }
    if (b.row >= (s.top - 6) && b.col >= s.left && b.col <= s.right) {
      du = randint(-2, -1);
      b.row = s.top - 5;
    } 
    b.row = b.row + du;
    b.col = b.col + rd;
    b.right = b.col;
    b.step = b.row;
    drawImageDMA(b.row, b.col, 18, 10, bomb2);
  }
}